import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import { NuqsAdapter } from "nuqs/adapters/next";
import ReduxProvider from "@/store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-main-black">
        <ReduxProvider>
          <NuqsAdapter>
            <Layout>{children}</Layout>
          </NuqsAdapter>
        </ReduxProvider>
      </body>
    </html>
  );
}
